app = "your-ai-todo-app"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    port = 8000
    protocol = "http"
    restart_limit = 0
    timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"

# nginx.conf - For production with reverse proxy
upstream fastapi {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name your-domain.com;
    
    location / {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    location /health {
        proxy_pass http://fastapi/health;
        access_log off;
    }
}
