apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-todo-app
  labels:
    app: ai-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-todo-app
  template:
    metadata:
      labels:
        app: ai-todo-app
    spec:
      containers:
      - name: ai-todo-app
        image: your-registry/ai-todo-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-todo-app-service
spec:
  selector:
    app: ai-todo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer